//--------------------------------------------------------------------------------
// Auto-generated by Migen (ea1eefe) & LiteX (05869be) on 2020-05-09 01:26:29
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#define CSR_BASE 0x82000000L
#define CSR_SIZE 0x00010000

#define SRAM_BASE 0x01000000L
#define SRAM_SIZE 0x00001000

#define ROM_BASE 0x00000000L
#define ROM_SIZE 0x00008000

#endif
