//--------------------------------------------------------------------------------
// Auto-generated by Migen (ea1eefe) & LiteX (05869be) on 2020-05-08 20:51:56
//--------------------------------------------------------------------------------
module top(
	input wire clk100,
	output wire led
);

wire sys_clk;
reg sys_rst = 1'd0;
reg [25:0] counter = 26'd0;

assign sys_clk = clk100;
assign led = counter[25];

always @(posedge sys_clk) begin
	counter <= (counter + 1'd1);
	if (sys_rst) begin
		counter <= 26'd0;
	end
end

endmodule
